### ISSUE TITLE
mac library not loaded: @rpath/libgflags.2.2.dylib

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/HybridSE#151]
# Intro
the `libhybridse_jsdk_core.dylib` can not load because it can not find gflags

# Affect Version
- v0.1.5-pre-4

# More
A wrong info included for libgflags:

```bash
$ otool -L libhybridse_jsdk_core.dylib
libhybridse_jsdk_core.dylib:
	@rpath/libhybridse_jsdk_core.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/glog/lib/libglog.0.dylib (compatibility version 0.0.0, current version 0.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	@rpath/libgflags.2.2.dylib (compatibility version 2.2.0, current version 2.2.2)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1355.22.0)
	/System/Library/Frameworks/CoreData.framework/Versions/A/CoreData (compatibility version 1.0.0, current version 977.3.0)
	/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.140.5)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1677.104.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
```

```log
21/07/06 13:21:39 ERROR LibraryLoader: Error while load libhybridse_jsdk_core.dylib from local resource
java.lang.UnsatisfiedLinkError: /private/var/folders/sn/jb1dhtjj505gb_tmj8kdplxw0000gn/T/temp-8494495444483409578libhybridse_jsdk_core.dylib: dlopen(/private/var/folders/sn/jb1dhtjj505gb_tmj8kdplxw0000gn/T/temp-8494495444483409578libhybridse_jsdk_core.dylib, 1): Library not loaded: @rpath/libgflags.2.2.dylib
  Referenced from: /private/var/folders/sn/jb1dhtjj505gb_tmj8kdplxw0000gn/T/temp-8494495444483409578libhybridse_jsdk_core.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com._4paradigm.hybridse.LibraryLoader.loadLibrary(LibraryLoader.java:89)
	at com._4paradigm.hybridse.HybridSeLibrary.initCore(HybridSeLibrary.java:38)
	at com._4paradigm.openmldb.batch.SparkPlanner.<init>(SparkPlanner.scala:39)
	at com._4paradigm.openmldb.batch.TestDate.$anonfun$new$1(TestDate.scala:60)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at com._4paradigm.openmldb.batch.SparkTestSuite.org$scalatest$BeforeAndAfter$$super$runTest(SparkTestSuite.scala:23)
	at org.scalatest.BeforeAndAfter.runTest(BeforeAndAfter.scala:203)
	at org.scalatest.BeforeAndAfter.runTest$(BeforeAndAfter.scala:192)
	at com._4paradigm.openmldb.batch.SparkTestSuite.runTest(SparkTestSuite.scala:23)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at com._4paradigm.openmldb.batch.SparkTestSuite.org$scalatest$BeforeAndAfter$$super$run(SparkTestSuite.scala:23)
	at org.scalatest.BeforeAndAfter.run(BeforeAndAfter.scala:258)
	at org.scalatest.BeforeAndAfter.run$(BeforeAndAfter.scala:256)
	at com._4paradigm.openmldb.batch.SparkTestSuite.run(SparkTestSuite.scala:23)
	at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1210)
	at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1257)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.scalatest.Suite.runNestedSuites(Suite.scala:1255)
	at org.scalatest.Suite.runNestedSuites$(Suite.scala:1189)
	at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
	at org.scalatest.Suite.run(Suite.scala:1144)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.main(Runner.scala:827)
	at org.scalatest.tools.Runner.main(Runner.scala)
```

**Comment by aceforeverd** [comment]
well according to https://blog.krzyzanowskim.com/2018/12/05/rpath-what/, 
we can inspect the `Runtime Search Path` via `otool -l libhybridse_jsdk_core.dylib | grep LC_RPATH -A2`
output is:
```bash
          cmd LC_RPATH
      cmdsize 64
         path /Users/runner/work/HybridSE/HybridSE/thirdparty/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 72
         path /Users/runner/work/HybridSE/HybridSE/thirdparty/lib64 (offset 12)
```

actually points to the building directory, while those directory may not exist in other runtime environment

**Comment by jingchen2222** [comment]
We can use mac third party package. https://github.com/jingchen2222/hybridsql-asserts/pull/7

**Comment by aceforeverd** [comment]
> We can use mac third party package. [jingchen2222/hybridsql-asserts#7](https://github.com/jingchen2222/hybridsql-asserts/pull/7)

yep, use the static version of glog and gflags

**Comment by aceforeverd** [comment]
old mac dylib have dependency problems:
```bash
thirdparty-mac/lib/libglog.0.4.0.dylib:
	/usr/local/opt/glog/lib/libglog.0.dylib (compatibility version 0.0.0, current version 0.4.0)
	/usr/local/opt/gflags/lib/libgflags.2.2.dylib (compatibility version 2.2.0, current version 2.2.2)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```
